kumuluzee:
  name: customer-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
